# Generated by Django 3.0.6 on 2020-05-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='reservation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
