# Generated by Django 3.0.6 on 2020-05-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0003_hotelmodel_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_image',
            field=models.ImageField(upload_to='images/hotels'),
        ),
    ]
