# Generated by Django 3.0.6 on 2020-05-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0004_auto_20200517_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationimagemodel',
            name='image',
            field=models.ImageField(upload_to='accommodation'),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='hotel_image',
            field=models.ImageField(upload_to='hotels'),
        ),
    ]
