# Generated by Django 3.0.6 on 2020-06-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0005_auto_20200517_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationmodel',
            name='number_of_beds',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six')]),
        ),
        migrations.CreateModel(
            name='HotelImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%hotel_name')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_reservation.HotelModel')),
            ],
        ),
    ]
