# Generated by Django 3.0.6 on 2020-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0006_auto_20200609_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimagemodel',
            name='image',
            field=models.ImageField(upload_to='images/hotels'),
        ),
    ]
