# Generated by Django 3.0.6 on 2020-06-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0007_auto_20200609_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccommodationImageModel',
        ),
    ]
