# Generated by Django 3.0.6 on 2020-06-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0009_wishmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishModel',
        ),
    ]
